[build]
  command = "pip install -r requirements-netlify.txt -t python"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

# Redirect all API requests to the Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# For SPA routing - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Specifies the directory where your functions are located
  directory = "netlify/functions"
  
  # Runtime settings
  [functions.runtime]
    # Specifies that we're using Python for our functions
    runtime = "python3.11"
    
    # Include all necessary files for the function
    included_files = ["**/*.py", "**/*.json", "**/*.txt"]
    
    # External node modules (empty for Python functions)
    external_node_modules = []

[dev]
  framework = "#custom"
  command = "uvicorn main:app --host 0.0.0.0 --port $PORT --reload"
  targetPort = 8000
  publish = "."
