[build]
  command = "pip install -r requirements-prod.txt"
  functions = "."
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[functions]
  directory = "."
  node_bundler = "esbuild"
